---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true 
  
  vars_files:
    - secrets.yml
  tasks:
  - name: clone a repo 
    git:
      repo: https://{{ token  }}@github.com/vinayreddykotla/vault.git
      dest: /opt/ansible/test-vault
