---
- name: this playbook installs packages
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
      name: ['git','gzip','gcc','telnet','make','wget']
      state: installed
