---
- name: this playbook installs packages
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip
     
